image: node

cache:
  paths:
  - node_modules/

stages:
  - build
  - pages

build:
  stage: build
  script:
  - npm install
  - cp src/config.json.sample src/config.json
  - npm run build
  artifacts:
    paths:
    - dist/

pages:
  dependencies:
    - build
  stage: pages
  script:
   - cp -r dist/ public/